### ISSUE TITLE
Unable to follow "Sandbox" links from Mesos UI

### ISSUE THREAD

**Issue by HelloGrayson** [breerly/compose-mesos#1]
After running the container example from the README and then going to the Mesos UI, this error is received when clicking on the "Sandbox" link for a running task:

```
Failed to connect to slave '20140927-181543-486543788-5050-1-0' on '7af7848f5538:5051'.
Potential reasons:
The slave's hostname, '7af7848f5538', is not accessible from your network
The slave's port, '5051', is not accessible from your network
The slave timed out or went offline
```

Screenshot:

![screen shot 2014-09-27 at 11 43 10 am](https://cloud.githubusercontent.com/assets/263587/4431740/3c2e4e36-4676-11e4-8696-bfa4e376ab77.png)

**Comment by fyarci** [comment]
i set hostname for slaves but sandbox links still now working

**Comment by smafra** [comment]
Hi Fellows.. I´ve got the same error. If the fix is to set MESOS_HOSTNAME.. somebody can tell us where and how to do that;

All best,

**Comment by gabnou** [comment]
doesn't work by adding MESOS_HOSTNAME to /etc/hosts

**Comment by breerly** [comment]
`localdocker` will have to point to the right IP.

**Comment by rushabh268** [comment]
You need to add the hostname to the /etc/hosts of the VM which is running the Mesos browser. In my case, it was my local linux and not the master so there was no benefit modifying the master's /etc/hosts

**Comment by pangbingqiang** [comment]
i have fixed it, do not use IE explorer and then in /etc/hosts must set the hostname of cluster for master and slaves

**Comment by blemagicleap** [comment]
After adding mesos master/slave hostname and IP addresses in the /etc/hosts file on both systems. Also restart mesos, zookeeper, and marthon services and the problem still exists.
